### ISSUE TITLE
Problem with mimemagic on setting up the server

### ISSUE THREAD

**Issue by NeonNature** [kuru-studio/kuru-studio-social-server#8]
# Bug Report

Bug: Problem with mimemagic on setting up server

## Description

The problem is with `mimemagic` versions being yanked out so the specified version in `Gem.lock` is not working anymore.

### Steps to Reproduce

1. Clone a new repo
2. `docker-compose build`

### Expected Result

The expected result was...

Being able to run `docker-compose build` without any error

### Actual Results

The actual result was...

![image](https://user-images.githubusercontent.com/21094190/141142730-9c9b8b19-8e41-4bfd-af0b-22a578200ba3.png)

**Comment by BosEriko** [comment]
We have a template.

**Comment by NeonNature** [comment]
> We have a template.

Updated with template

**Comment by BosEriko** [comment]
It's worth mentioning that mimemagic stopped working because of license issue so the particular version was yanked. The solution was to pull the exact version from GitHub.

https://github.com/kuru-studio/kuru-studio-social-server/pull/9/files
